version: "3"

networks:
  drone:
    driver: bridge

services:
  server:
    image: drone/drone:2
    container_name: drone_server
    restart: always
    ports:
      - "3000:80"
    networks:
        - drone
    volumes:
        - ./data/drone_server:/data
    env_file:
      - .env

  runner:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    restart: always
    depends_on:
      - server
    networks:
        - drone
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
